### PR TITLE
Add Indonesia spatial index

### PR DESCRIPTION
**Pull request by nickmmurphy**

### CODE REVIEW

**Review by ect123 — COMMENTED** [review]
Hi @nickmmurphy is this the entire index or only the portion that's included in UBC's map collection?

**Comment by nickmmurphy** [comment]
> Hi @nickmmurphy is this the entire index or only the portion that's included in UBC's map collection?

Hi @ect123, yes this is for use with the Map-O-Matic. The full spatial index for Indonesia also exists, but without any collection data.

**Comment by ect123** [comment]
Great! If possible, please add the polygons and whatever OIM elements there are for those, plus the `available = false` element. The reason for this is for (1) if we ever receive these maps, (2) so the indexes can be repurposed by others, and (3) so that researchers know that these sheets might exist somewhere. Thanks!

**Comment by nickmmurphy** [comment]
@ect123 The new file has been added, and the column names have been changed to show the LOC heading. Let me know if any other changes are needed!

**Review by ect123 — APPROVED** [review]

**Pull request merged**
